name: "Publish World"

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  Setup:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/restore-cache
        id: cache-dependencies

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

  Publish:
    name: Publish worlds
    runs-on: ubuntu-latest
    needs: Setup
    env:
      DEVELOPER_TOKEN: ${{ secrets.DEVELOPER_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/restore-cache

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            example_1_hello_hdk:
              - 'example_1_hello_hdk/**'
            example_2_builder:
              - 'example_2_builder/**'            
            example_3_game_mechanics:
              - 'example_3_game_mechanics/**'                
            example_4_meshes_and_avatars:
              - 'example_4_meshes_and_avatars/**'                
            example_5_procedural_rotation:
              - 'example_5_procedural_rotation/**'                
            example_6_media_and_interaction:
              - 'example_6_media_and_interaction/**'               
            example_7_signals:
              - 'example_7_signals/**'
            city:
              - 'city/**'
            dia-house:
              - 'dia-house/**'
            dragons-nest:
              - 'dragons-nest/**'
            getting-started:
              - 'getting-started/**'
            hibertropolis:
              - 'hibertropolis/**'
            hub:
              - 'hub/**'
            logic-gates:
              - 'logic-gates/**'
            hiber-dig:
              - 'hiber-dig/**'
            obby-islands:
              - 'obby-islands/**'
            starship-hiberion:
              - 'starship-hiberion/**'

      - name: Upload 'all-assets'
        if: steps.changes.outputs.all-assets == 'true'
        uses: hiber3d/publish@latest
        with:
          world: "all-assets"

      - name: Upload 'example_1_hello_hdk'
        if: steps.changes.outputs.example_1_hello_hdk == 'true'
        uses: hiber3d/publish@latest
        with:
          world: "example_1_hello_hdk"

      - name: Upload 'example_2_builder'
        if: steps.changes.outputs.example_2_builder == 'true'
        uses: hiber3d/publish@latest
        with:
          world: "example_2_builder"

      - name: Upload 'example_3_game_mechanics'
        if: steps.changes.outputs.example_3_game_mechanics == 'true'
        uses: hiber3d/publish@latest
        with:
          world: "example_3_game_mechanics"

      - name: Upload 'example_4_meshes_and_avatars'
        if: steps.changes.outputs.example_4_meshes_and_avatars == 'true'
        uses: hiber3d/publish@latest
        with:
          world: "example_4_meshes_and_avatars"

      - name: Upload 'example_5_procedural_rotation'
        if: steps.changes.outputs.example_5_procedural_rotation == 'true'
        uses: hiber3d/publish@latest
        with:
          world: "example_5_procedural_rotation"

      - name: Upload 'example_6_media_and_interaction'
        if: steps.changes.outputs.example_6_media_and_interaction == 'true'
        uses: hiber3d/publish@latest
        with:
          world: "example_6_media_and_interaction"

      - name: Upload 'example_7_signals'
        if: steps.changes.outputs.example_7_signals == 'true'
        uses: hiber3d/publish@latest
        with:
          world: "example_7_signals"

      - name: Upload 'city'
        if: steps.changes.outputs.city == 'true'
        uses: hiber3d/publish@latest
        with:
          world: "city"

      - name: Upload 'dia-house'
        if: steps.changes.outputs.dia-house == 'true'
        uses: hiber3d/publish@latest
        with:
          world: "dia-house"
        
      - name: Upload 'dragons-nest'
        if: steps.changes.outputs.dragons-nest == 'true'
        uses: hiber3d/publish@latest
        with:
          world: "dragons-nest"

      - name: Upload 'getting-started'
        if: steps.changes.outputs.getting-started == 'true'
        uses: hiber3d/publish@latest
        with:
          world: "getting-started"
  
      - name: Upload 'hibertropolis'
        if: steps.changes.outputs.hibertropolis == 'true'
        uses: hiber3d/publish@latest
        with:
          world: "hibertropolis"

      - name: Upload 'hub'
        if: steps.changes.outputs.hub == 'true'
        uses: hiber3d/publish@latest
        with:
          world: "hub"

      - name: Upload 'logic-gates'
        if: steps.changes.outputs.logic-gates == 'true'
        uses: hiber3d/publish@latest
        with:
          world: "logic-gates"

      - name: Upload 'hiber-dig'
        if: steps.changes.outputs.hiber-dig == 'true'
        uses: hiber3d/publish@latest
        with:
          world: "hiber-dig"

      - name: Upload 'obby-islands'
        if: steps.changes.outputs.obby-islands == 'true'
        uses: hiber3d/publish@latest
        with:
          world: "obby-islands"

      - name: Upload 'starship-hiberion'
      if: steps.changes.outputs.starship-hiberion == 'true'
      uses: hiber3d/publish@latest
      with:
        world: "starship-hiberion"
